config/routes.rb
Rails.application.routes.draw do
  resources :gemtutorials do  
    resources :steps
  end

  resources :steps
  
  root 'gemtutorials#index'

end

app/models/gemtutorial.rb
class Gemtutorial < ActiveRecord::Base
	has_many :steps
end

app/models/step.rb
class Step < ActiveRecord::Base
	belongs_to :gemtutorial
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gemtutorials_controller.rb
class GemtutorialsController < ApplicationController
  before_action :set_gemtutorial, only: [:show, :edit, :update, :destroy]

  # GET /gemtutorials
  # GET /gemtutorials.json
  def index
    @gemtutorials = Gemtutorial.all
  end

  # GET /gemtutorials/1
  # GET /gemtutorials/1.json
  def show
  end

  # GET /gemtutorials/new
  def new
    @gemtutorial = Gemtutorial.new
  end

  # GET /gemtutorials/1/edit
  def edit
  end

  # POST /gemtutorials
  # POST /gemtutorials.json
  def create
    @gemtutorial = Gemtutorial.new(gemtutorial_params)

    respond_to do |format|
      if @gemtutorial.save
        format.html { redirect_to @gemtutorial, notice: 'Gemtutorial was successfully created.' }
        format.json { render :show, status: :created, location: @gemtutorial }
      else
        format.html { render :new }
        format.json { render json: @gemtutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gemtutorials/1
  # PATCH/PUT /gemtutorials/1.json
  def update
    respond_to do |format|
      if @gemtutorial.update(gemtutorial_params)
        format.html { redirect_to @gemtutorial, notice: 'Gemtutorial was successfully updated.' }
        format.json { render :show, status: :ok, location: @gemtutorial }
      else
        format.html { render :edit }
        format.json { render json: @gemtutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gemtutorials/1
  # DELETE /gemtutorials/1.json
  def destroy
    @gemtutorial.destroy
    respond_to do |format|
      format.html { redirect_to gemtutorials_url, notice: 'Gemtutorial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gemtutorial
      @gemtutorial = Gemtutorial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gemtutorial_params
      params.require(:gemtutorial).permit(:name, :repo, :description, :genre, :score)
    end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_step, only: [:show, :edit, :update, :destroy]

  # GET /steps
  # GET /steps.json
  def index
    @steps = Step.all
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
  end

  # GET /steps/new
  def new
    @step = Step.new
  end

  # GET /steps/1/edit
  def edit
  end

  # POST /steps
  # POST /steps.json
  def create
    @step = Step.new(step_params)

    respond_to do |format|
      if @step.save
        format.html { redirect_to @step, notice: 'Step was successfully created.' }
        format.json { render :show, status: :created, location: @step }
      else
        format.html { render :new }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /steps/1
  # PATCH/PUT /steps/1.json
  def update
    respond_to do |format|
      if @step.update(step_params)
        format.html { redirect_to @step, notice: 'Step was successfully updated.' }
        format.json { render :show, status: :ok, location: @step }
      else
        format.html { render :edit }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step.destroy
    respond_to do |format|
      format.html { redirect_to steps_url, notice: 'Step was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_step
      @step = Step.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def step_params
      params.require(:step).permit(:path, :code, :note, :sequence)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/gemtutorials_helper.rb
module GemtutorialsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/gemtutorials/_form.html.erb
<%= form_for(@gemtutorial) do |f| %>
  <% if @gemtutorial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gemtutorial.errors.count, "error") %> prohibited this gemtutorial from being saved:</h2>

      <ul>
      <% @gemtutorial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :repo %><br>
    <%= f.text_field :repo %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gemtutorials/edit.html.erb
<h1>Editing Gemtutorial</h1>

<%= render 'form' %>

<%= link_to 'Show', @gemtutorial %> |
<%= link_to 'Back', gemtutorials_path %>

app/views/gemtutorials/index.html.erb
<h1>Gemtutorials Index</h1>


<% @gemtutorials.each do |gem| %>


<ul class="surveys grid">
  <li class="survey-item">
    
    <span class="survey-country grid-only">
      <%= gem.name %>
    </span>


    <span class="survey-country list-only">
      <%= gem.name %>
    </span>
    
    <span class="survey-name">
      <%= link_to "", gem.repo, {class: "embedly-card"} %>
    </span>

    <span>
    <h3> <%= gem.description %> </h3>
    </span>
    
    <div class = "pull-right" >   
    <span>

    
      <button class = 'btn btn-primary'> Learn more... </button>

    </span>
    </div>
  </li>

</ul>  
<% end %>

    



<!--  -->




<p id="notice"><%= notice %></p>



<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Repo</th>
      <th>Description</th>
      <th>Genre</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gemtutorials.each do |gemtutorial| %>
      <tr>
        <td><%= gemtutorial.name %></td>
        


        <td>

          <%= link_to "", gemtutorial.repo, {class: "embedly-card"} %>
        </td>
        


        <td><%= gemtutorial.description %></td>
        <td><%= gemtutorial.genre %></td>
        <td><%= gemtutorial.score %></td>
        <td><%= link_to 'Show', gemtutorial %></td>
        <td><%= link_to 'Edit', edit_gemtutorial_path(gemtutorial) %></td>
        <td><%= link_to 'Destroy', gemtutorial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gemtutorial', new_gemtutorial_path %>

app/views/gemtutorials/new.html.erb
<h1>New Gemtutorial</h1>

<%= render 'form' %>

<%= link_to 'Back', gemtutorials_path %>

app/views/gemtutorials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gemtutorial.name %>
</p>

<p>
  <strong>Repo:</strong>
  <%= @gemtutorial.repo %>
</p>

<p>
  <strong>Description:</strong>
  <%= @gemtutorial.description %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @gemtutorial.genre %>
</p>

<p>
  <strong>Score:</strong>
  <%= @gemtutorial.score %>
</p>

<%= link_to 'Edit', edit_gemtutorial_path(@gemtutorial) %> |
<%= link_to 'Back', gemtutorials_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>GemTutorail</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<script src="http://cdn.embed.ly/jquery.embedly-3.1.1.min.js" type="text/javascript"></script>


	<!-- install platform.js -->
	<script>
	(function(w, d){
		var id='embedly-platform', n = 'script';
		if (!d.getElementById(id)){
			w.embedly = w.embedly || function() {(w.embedly.q = w.embedly.q || []).push(arguments);};
			var e = d.createElement(n); e.id = id; e.async=1;
			e.src = ('https:' === document.location.protocol ? 'https' : 'http') + '://cdn.embedly.com/widgets/platform.js';
			var s = d.getElementsByTagName(n)[0];
			s.parentNode.insertBefore(e, s);
		}
	})(window, document);

	</script>

</head>
<body>
	<div class = "container"> 
		<br>
		<nav class="navbar navbar-default">
			<div class="container-fluid">
				<div class="navbar-header">
					<a class="navbar-brand" href="#">
						GemTutorail
					</a>
					<form class="navbar-form navbar-left" role="search">
						<div class="form-group">
							<input type="text" class="form-control" placeholder="Search">
						</div>
						<button type="submit" class="btn btn-default">Submit</button>
					</form>
				</div>
			</div>
		</nav>

		
		
		



     




		<%= yield %>

	</div>

</body>
<script type="text/javascript">
jQuery(document).ready(function($) {
		// $('a').embedly({key: '6030892a3e1c4251b65fd50e420d7ae7'});	
	});
</script>



</html>

app/views/steps/_form.html.erb
<%= form_for(@step) do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :path %><br>
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_area :code %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_field :note %>
  </div>
  <div class="field">
    <%= f.label :sequence %><br>
    <%= f.number_field :sequence %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing Step</h1>

<%= render 'form' %>

<%= link_to 'Show', @step %> |
<%= link_to 'Back', steps_path %>

app/views/steps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Steps</h1>

<table>
  <thead>
    <tr>
      <th>Path</th>
      <th>Code</th>
      <th>Note</th>
      <th>Sequence</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @steps.each do |step| %>
      <tr>
        <td><%= step.path %></td>
        <td><%= step.code %></td>
        <td><%= step.note %></td>
        <td><%= step.sequence %></td>
        <td><%= link_to 'Show', step %></td>
        <td><%= link_to 'Edit', edit_step_path(step) %></td>
        <td><%= link_to 'Destroy', step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Step', new_step_path %>

app/views/steps/new.html.erb
<h1>New Step</h1>

<%= render 'form' %>

<%= link_to 'Back', steps_path %>

app/views/steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Path:</strong>
  <%= @step.path %>
</p>

<p>
  <strong>Code:</strong>
  <%= @step.code %>
</p>

<p>
  <strong>Note:</strong>
  <%= @step.note %>
</p>

<p>
  <strong>Sequence:</strong>
  <%= @step.sequence %>
</p>

<%= link_to 'Edit', edit_step_path(@step) %> |
<%= link_to 'Back', steps_path %>